name: build and deploy

on:
  push:
    branches:
      - main
jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: production_environment
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          build-args: |
            REACT_APP_API_URL=http://front.bbbs.fun/api/v1
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bbbs-frontend:latest  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    environment: production_environment
    steps:
      -
        name: execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_FOLDER }}
            export COMPOSE_FILE=${{ secrets.COMPOSE_FILE }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/bbbs-frontend:latest
            docker-compose down
            docker-compose up -d --build
